blank_issues_enabled: false
contact_links:
  - name: Installer
    url: https://github.com/flybywiresim/installer/issues/new/choose
    about: File a bug report or suggest a new feature for the installer
