[package]
name = "systems"
version = "0.1.0"
authors = ["FlyByWire Simulations"]
edition = "2018"

[dependencies]
uom = "0.30.0"
rand = "0.8.0"
ntest = "0.7.2"
plotlib = "0.5.1"
rustplotlib = "0.0.4"
