name: PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/flybywiresim/dev-env:latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: install
        run: npm install --no-optional
      - name: lint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/flybywiresim/dev-env:latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: build
        run: |
          ./scripts/setup.sh
          ./scripts/build.sh

          mkdir tmp_A32NX
          mv A32NX tmp_A32NX/
          mv tmp_A32NX A32NX
      - uses: actions/upload-artifact@v2
        with:
          name: A32NX
          path: A32NX
